# Generated by Django 4.0.6 on 2022-07-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_alter_likecomment_comment_alter_likecomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_on_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
