# Generated by Django 4.0.6 on 2023-05-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0006_post_is_on_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
